# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('website', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('homeadd', models.CharField(default='N/A', max_length=200)),
                ('dob', models.DateField(default='2000-1-1')),
                ('contact', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=3)),
                ('yoc1', models.IntegerField(default='2000')),
                ('board1', models.CharField(default='', max_length=200)),
                ('percentage1', models.IntegerField(default='0')),
                ('yoc2', models.IntegerField(default='2000')),
                ('board2', models.CharField(default='', max_length=200)),
                ('percentage2', models.IntegerField(default='0')),
                ('yoc3', models.IntegerField(blank=True, default='2000')),
                ('percentage3', models.IntegerField(blank=True, default='0')),
                ('college', models.CharField(blank=True, default='N/A', max_length=100)),
                ('course', models.CharField(blank=True, default='N/A', max_length=20)),
                ('company_i', models.CharField(blank=True, default='N/A', max_length=200)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('profile_i', models.CharField(blank=True, default='N/A', max_length=20)),
                ('company_i2', models.CharField(blank=True, default='N/A', max_length=200)),
                ('duration2', models.IntegerField(blank=True, default=0)),
                ('profile_i2', models.CharField(blank=True, default='N/A', max_length=20)),
                ('work', models.CharField(blank=True, default='N/A', max_length=100)),
                ('title_p', models.CharField(blank=True, default='N/A', max_length=30)),
                ('description_p', models.CharField(blank=True, default='N/A', max_length=100)),
                ('skills', models.CharField(default='', max_length=100)),
                ('git_hub', models.URLField(blank=True, default='')),
                ('linked_in', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
